#Spring Boot Config
server:
  #ssl:
  #key-store: C:/Program Files/tmcssl/2894343_guilongkeji.com.cn.pfx
  #key-store-password: m85e0eH7
  servlet:
    session:
      timeout: 720
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://cdb-1lmq810s.cd.tencentcdb.com:10055/canteen?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: xgl020331
    druid:
      initial-size: 1
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      suffix: .html
      request-context-attribute: request
      charset: UTF-8
resources:
  static-locations: classpath:classpath:/resources/,classpath:/templates/,classpath:/public/,classpath:/static/

#MyBatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.app.mapper

#logging
logging:
  file:
    path: C:\app\log
